openapi: 3.0.0
info:
  title: Sample API
  description: A sample API to demonstrate Swagger UI integration.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/hello
    description: Local server

paths:
  /api/hello:
    get:
      summary: Get a hello message
      description: Returns a simple hello message.
      responses:
        '200':
          description: A JSON object with a hello message.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello, World!
